name: Bug Report
description: Report an issue with the application
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please fill out with as much detail as possible
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Explain what you saw versus what happened.
    validations:
      required: true
  - type: dropdown
    id: Setup-type
    attributes:
      label: What setup are you seeing the problem on?
      multiple: true
      options:
        - Executable
        - Virtual Environment
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce?
      description: What steps have you taken to see the bug? (OPTIONAL)
      placeholder: 1. ...
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other relevant information
      description: |
        Feel free to give any more information that doesn't fit the above text boxes.

        Tip: You can attach files by clicking this textbox and dragging in files
    validations:
      required: false
